
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    enable: true
  redis:
    host: localhost
    port: 6379
    timeout: 60000

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example: DEBUG
  file:
    name: logs/application.log